support LRU and LFU eviction
HDT3213/godis pull request #167
Opened 2023-04-27 06:49 UTC by suger-no

因为config中没有内存设置，所以逐出方法没有使用

2023-04-29 17:34 UTC, HDT3213 requested changes

2023-04-29 17:34 UTC, HDT3213 commented on database/database.go
> +	if db.evictionPolicy.IsAllKeys() == false {
通常写作 `if !db.evictionPolicy.IsAllKeys()`

2023-04-29 17:34 UTC, HDT3213 commented on database/database.go
> +		db.data.ForEach(func(key string, val interface{}) bool {
ttlMap 也有RandomDistinctKeys方法的

2023-04-29 17:34 UTC, HDT3213 commented on database/database.go
> +func (db *DB) RandomDistinctKeysForEviction(limit int) []string {
这段代码只会调用一次，不需要抽象成函数

2023-04-29 17:34 UTC, HDT3213 commented on eviction/lfu.go
> +func GetLFUCounter(lfu int32) uint8 {
此函数不需要公开，应为私有

2023-04-29 17:34 UTC, HDT3213 commented on eviction/lfu.go
> +func LFULogIncr(counter uint8) uint8 {
此函数应私有

2023-04-29 17:34 UTC, HDT3213 commented on eviction/lfu.go
> +func LFUDecrAndReturn(lfu int32) int32 {
此函数应私有

2023-04-29 17:34 UTC, HDT3213 commented on eviction/lfu.go
> +func LFUTimeElapsed(ldt int32) int32 {
此函数应私有

2023-04-29 17:34 UTC, HDT3213 commented on interface/eviction/enviction_policy.go
interface/eviction, eviction/lru, eviction/lfu 放入 database 包内即可，不需要公开到整个项目。
以及文件名拼错了 enviction_policy.go

2023-04-29 17:34 UTC, HDT3213 commented on database/database.go
> +func (db *DB) MakeEviction(keys []string) {
MakeEviction 函数应私有，作为 MakeXXX 却无返回值就很别扭。可以改为 initEvitionMark

2023-04-29 17:34 UTC, HDT3213 commented on database/database.go
> +func (db *DB) UpdateMark(keys []string) {
1. 函数应私有
2. 这是 DB 的函数不是 evictionPolicy 的函数，函数名中带上 eviction 否则不知道更新的是什么 Mark. 
 
UpdateMark -> updateEvictionMark

2023-04-29 17:47 UTC, HDT3213 commented
1. bug fix:RewriteAof will panic if appendonly property is no 和 add Command command 两个提交已经合并了不要重复 PR。
2. 请为新功能添加自动测试
3. eviction 作为 database 的一个功能放入 database 包即可，无需添加到 interface 包。 可以添加 database/eviction 包，并在其中放入 interface.go,lru.go,lfu.go
4. 请注意函数的可见范围

2023-04-29 17:54 UTC, HDT3213 commented
可以使用 `process.NewProcess(int32(os.Getpid()))` 获取自身进程的内存使用量，以此作为判断是否逐出的根据。

2023-04-30 04:24 UTC, suger-no commented
> 可以使用 `process.NewProcess(int32(os.Getpid()))` 获取自身进程的内存使用量，以此作为判断是否逐出的根据。

有几个问题，
如果拿到一个key要逐出，那么每次都要调用一次gc，关于gc的问题
还有逐出过程中需要加锁，性能瓶颈会在这产生？
process没发现这个包

2023-05-05 11:29 UTC, HDT3213 commented
evitction 应该写入 aof 并传播到 slave

2023-05-05 11:44 UTC, HDT3213 commented
redis 在达到 maxmemory 时不会只淘汰一个 key, 参考 [getMaxmemoryState](https://github.com/CN-annotation-team/redis7.0-chinese-annotated/blob/8a39f32154e25910f0a0ad0c3c026b09d33d5aee/src/evict.c#L467) 计算 mem_tofree

2023-05-05 11:48 UTC, HDT3213 commented
请阅读 #146

2023-05-17 02:05 UTC, closed without merging