add config command
HDT3213/godis pull request #174
Opened 2023-05-10 12:08 UTC by cheny-alf

2023-05-12 09:34 UTC, cheny-alf commented
@HDT3213 可以帮review下吗，顺便看看为什么pipeline 中有个测试过不了呢

2023-05-12 09:39 UTC, HDT3213 commented
```
=== RUN   TestConfigSet
    assert.go:146: expected $3
        128
        , actually &{[%!s(*protocol.BulkReply=&{[109 97 120 99 108 105 101 110 116 115]}) %!s(*protocol.BulkReply=&{[48]})]}, at /home/runner/work/godis/godis/database/config_test.go:47
--- FAIL: TestConfigSet (0.56s)
```

go 里面每次  for-each map 的顺序是随机的， 所以 setConfig 每次返回的 MultiBulkReply 是不一样的

2023-05-14 01:23 UTC, HDT3213 requested changes

2023-05-14 01:23 UTC, HDT3213 commented on config/config.go
> +var PropertiesMap map[string]string
没有必要把 config 存两份， 全换成 map 或者用反射改 struct 都行， 毕竟 config struct 是低频操作

2023-05-14 01:23 UTC, HDT3213 commented on config/config.go
> +	Maxmemory_policyConfig = "maxmemory_policy"
哪有 CamelCase + snake 混合命名的

2023-05-14 01:23 UTC, HDT3213 commented on config/config.go
> +)
没实现的类别先不用加

2023-05-14 01:23 UTC, HDT3213 commented on config/config.go
> +	case SaveConfig, AppendonlyConfig, DirConfig, MaxmemoryConfig, Maxmemory_policyConfig, DbfilenameConfig, BindConfig, DaemonizeConfig:
immutable == false 意为这些配置项可变，没弄反吗？

2023-05-14 01:23 UTC, HDT3213 commented on config/config.go
> +	SaveConfig             = "save"
go lint 要求所有 public 的变量、常量、类型、函数都应有注释

2023-05-14 01:23 UTC, HDT3213 commented on database/config.go
> +	return protocol.MakeMultiRawReply(result)
直接用 MakeMultiBulkReply 不就好了吗

2023-05-14 01:23 UTC, HDT3213 commented on database/config.go
> +		if _, ok := updateMap[parameter]; ok {
并发修改 updateMap 不加锁会 fatal 的。。

2023-05-14 01:25 UTC, HDT3213 commented
请阅读 #146：
- 请确保您的代码进行了 gofmt，并通过了 golint 的检测。
- 请保持 git 时间线的整洁。一个 PR 中应只包含一个或数个 commit，请在提 PR 前 squash 掉开发过程中产生的、不需要保留的 commit

2023-05-14 01:30 UTC, HDT3213 commented on config/config.go
> +	case SaveConfig, AppendonlyConfig, DirConfig, MaxmemoryConfig, Maxmemory_policyConfig, DbfilenameConfig, BindConfig, DaemonizeConfig:
因为可变的配置是少数，这里最好反过来枚举可变配置，默认不可变。这样在新增配置项时即使忘记修改 IsImmutableConfig 也不会出大问题

2023-05-14 01:33 UTC, HDT3213 requested changes

2023-05-14 01:33 UTC, HDT3213 commented on database/config.go
> +		isImmutable := config.IsImmutableConfig(parameter)
反了哦

2023-05-14 01:33 UTC, HDT3213 commented on database/config.go
> +func ExecConfigCommand(args [][]byte) redis.Reply {
exec 函数私有就可以了

2023-05-24 12:14 UTC, closed without merging