add zlexcount command to zset
HDT3213/godis pull request #189
Opened 2023-06-04 09:22 UTC by Damonslh

2023-06-04 09:27 UTC, Damonslh commented
@HDT3213 为啥失败了呢？

2023-06-05 14:55 UTC, HDT3213 requested changes

2023-06-05 14:55 UTC, HDT3213 commented on database/sortedset.go
> +	if n != 3 {
registerCommand 里设了 arity 之后 execNormalCommand 会统一校验参数个数的， 不需要再校验一次

2023-06-05 14:55 UTC, HDT3213 commented on database/sortedset.go
> +		sortedSet.ForEach(minRank, sortedSet.Len(), false, func(element *SortedSet.Element) bool {
ForEach 会再查找一次 minRank 白白浪费时间， 建议直接加个 ForEachByLex

2023-06-05 14:55 UTC, HDT3213 commented on database/sortedset.go
> +		sortedSet.ForEach(minRank, maxRank, false, func(element *SortedSet.Element) bool {
好了，ForEach 又查找了一次 minRank 的位置

2023-06-05 14:55 UTC, HDT3213 commented on database/sortedset.go
> +				minRank++
要实现 offset 比较一下 sortedSet.Len() 和 minRank+ offset 的大小不就可以了吗？没必要真的扫一次啊

2023-06-05 14:55 UTC, HDT3213 commented on database/sortedset.go
> +		sortedSet.RemoveByRank(minRank, maxRank)
同样的问题，RemoveByRank 又查找了一次

2023-06-05 14:55 UTC, HDT3213 commented on database/sortedset.go
> +	zset.ForEach(0, zset.Len(), false, func(ele *SortedSet.Element) bool {
啊，不需要线性遍历吧

2023-06-10 13:35 UTC, HDT3213 commented on database/sortedset.go
> +	fmt.Println(min, max)
hello

2023-06-10 13:35 UTC, HDT3213 commented on datastruct/sortedset/border.go
> +	greater(interface{}) bool
我本来想声明成 `greater(*Element) bool` 的, 这样 remove, range 这些函数就不需要再写一次了

2023-06-13 02:13 UTC, HDT3213 requested changes

2023-06-13 02:13 UTC, HDT3213 commented on datastruct/sortedset/skiplist.go
> +	switch min.getValue().(type) {
给  Border 加一个 isIntersected(Border) 函数吧。 如果日后要新增其他 border 实现，很容易忘记这里需要修改

2023-06-15 12:55 UTC, merged