add scan command
HDT3213/godis pull request #199
Opened 2023-07-24 13:11 UTC by NaNShaner

add scan command

2023-07-29 08:36 UTC, HDT3213 requested changes

2023-07-29 08:36 UTC, HDT3213 commented on database/keys.go
> +func execScan(db *DB, args [][]byte) redis.Reply {
scan 的参数有 MATCH，COUNT, TYPE 3个，实际执行 scan 的函数签名应该是 scan0(cursor, pattern, count, typ)。
现在的解析命令行逻辑过于晦涩， 可以参考一下 [execSet](https://github.com/HDT3213/godis/blob/3d53ba2d1d099841d555ead0b366171d353aefba/database/string.go#L123) 的实现

2023-07-29 08:36 UTC, HDT3213 commented on datastruct/dict/concurrent.go
> +	remainingKeys := dict.table[cursor:]
table 中取出来的是 shard, 为啥起名叫 remainingKeys?

2023-07-29 08:36 UTC, HDT3213 commented on datastruct/dict/concurrent.go
> +func (dict *ConcurrentDict) ScanKeys(cursor, count int, matchKey string) ([]string, int) {
matchKey -> pattern

2023-07-29 08:36 UTC, HDT3213 commented on datastruct/dict/concurrent.go
> +						pattern, err := wildcard.CompilePattern(matchKey)
CompilePattern 执行一次就可以了。。

2023-07-29 08:36 UTC, HDT3213 commented on datastruct/dict/concurrent.go
> +	r := make(map[string]struct{})
不要使用过于简单的变量名

2023-07-29 08:36 UTC, HDT3213 commented on datastruct/dict/concurrent.go
> +				if count <= i {
scan 命令不保证返回的元素数一定等于 count 参数，但是保证从遍历开始直到完整遍历结束期间， 一直存在于数据集内的所有元素都会被返回。如果到了 count 就中止的话，当前shard 中可能有一些 key 在遍历期间一直存在但因为遍历中止未被返回。

所以应完整遍历shard, 当 len(result) >= count 后返回即可。

```
for _, shard := range shards {
    for k, _ := range shard.m {
          result.add(key)
    } 
    if len(result) >= count {
          break
    }
} 
```

2023-07-29 08:38 UTC, HDT3213 commented
两个大问题

1. 解析命令行逻辑过于晦涩， 可以参考一下 [execSet](https://github.com/HDT3213/godis/blob/3d53ba2d1d099841d555ead0b366171d353aefba/database/string.go#L123) 的实现

2. scan 命令不保证返回的元素数一定等于 count 参数，但是保证： 「从遍历开始直到完整遍历结束期间， 一直存在于数据集内的所有元素都会被返回」。如果到了 count 就中止的话，当前shard 中可能有一些 key 在遍历期间一直存在但因为遍历中止未被返回。

所以应完整遍历shard, 当 len(result) >= count 后返回即可。

```
for _, shard := range shards {
    for k, _ := range shard.m {
          result.add(key)
    } 
    if len(result) >= count {
          break
    }
} 
```

2023-07-29 08:38 UTC, HDT3213 commented on datastruct/dict/concurrent.go
> +	i := 0
直接用 len(r) 不就行了

2023-08-05 13:25 UTC, NaNShaner commented
按照您的建议做了一些修改，貌似test failed。略有些不解🤔。

2023-08-09 01:49 UTC, HDT3213 commented
```
=== RUN   TestScan


    keys_test.go:332: test failed




--- FAIL: TestScan (0.05s)
```

新加的 TestScan 挂了

2023-08-09 07:42 UTC, NaNShaner commented
我本地跑是正常的

![image](https://github.com/HDT3213/godis/assets/20882547/9e64ad88-c967-4315-b24a-91fd35050879)

2023-08-13 01:59 UTC, NaNShaner commented
知道了， 每次scan迭代返回的key是无序的，所以在test比对的时候会偶发不一致。

2023-08-13 13:41 UTC, HDT3213 requested changes

2023-08-13 13:41 UTC, HDT3213 commented on database/keys.go
> +func scanWithArg(db *DB, args [][]byte, match bool) redis.Reply {
函数签名改成： execScan0(cursor, pattern, count, typ)

2023-08-13 13:41 UTC, HDT3213 commented on database/keys.go
> +func execScanWithArg(db *DB, args [][]byte, argType int) redis.Reply {
函数签名改成 execScan0(cursor string, pattern string, count int)
type 参数可以先不加

2023-08-13 13:41 UTC, HDT3213 commented on database/keys.go
> +	const (
```
var count int
var pattern string
for i := 1; i < argsNum; i++ {
	arg := strings.ToLower(string(args[i]))
	if arg == "count" {
              count = itoa(args[i+1])
              i++
        }
        ....
}
execScan0(cursor, pattern, count)
```

这样不就完事了，为啥写这么麻烦

2023-08-13 13:41 UTC, HDT3213 commented on database/keys.go
> +func execScanWithArg(db *DB, args [][]byte, argType int) redis.Reply {
上次说的 type 不是参数类型， scan 命令可以根据 string/list/hash/set/sortedset 类型进行过滤.

2023-08-13 13:41 UTC, HDT3213 commented on datastruct/dict/concurrent.go
> +				if len(m) >= count {
https://github.com/HDT3213/godis/pull/199#discussion_r1278269017

遍历完 shard 再返回

2024-05-05 11:35 UTC, closed without merging